
export var dogBreeds =
  ['Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akbash',
  'Akita',
  'Alaskan Malamute',
  'American Eskimo',
  'American Cocker Spaniel',
  'American Bulldog',
  'American Staffordshire Terrier',
  'Anatolian Shepherd',
  'Australian Cattle Dogs',
  'Australian Shepherd',
  'Australian Terrier',
  'Basset Hound',
  'Beagle',
  'Bedlington Terrier',
  'Belgian Shepherd',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Bloodhound',
  'Boerboel',
  'Border Collie',
  'Border Terrier',
  'Boxer',
  'Bullmastiff',
  'Cairn',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Chihuahua',
  'Chow Chow',
  'Collie',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'English Cocker Spaniel',
  'English Shepherd',
  'English Springer Spaniel',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Great Dane',
  'Greyhound',
  'Havanese',
  'Icelandic Sheepdog',
  'Irish Setter',
  'Jack Russell Terrier',
  'Kishu',
  'Labrador Retriever',
  'Labradoodle',
  'Lhasa Apso',
  'Maltese',
  'Mastiff',
  'Miniature Dachshund',
  'Newfoundland',
  'Norfolk Terrier',
  'Norwegian Lundehund',
  'Old English Sheepdog',
  'Papillon',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Pomeranian',
  'Poodle',
  'Pug',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Scottish Terrier',
  'Shetland Sheepdog / Sheltie',
  'Shih Tzu',
  'Siberian Husky',
  'Staffordshire Bull Terrier',
  'Schnauzer',
  'Tibetan Mastiff',
  'Tibetan Terrier',
  'Toy Fox Terrier',
  'Vizsla',
  'Weimaraner',
  'Welsh Terrier',
  'West Highland White Terrier / Westie',
  'Whippet',
  'Wirehaired Pointing Griffon',
  'Xoloitzcuintli / Mexican Hairless',
  'Yorkshire Terrier'];


export var catBreeds = ['Abyssinian',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Balinese',
  'Bombay',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Chausie',
  'Cornish Rex',
  'Cymric',
  'Devon Rex',
  'Domestic Long Hair',
  'Domestic Medium Hair',
  'Domestic Shorthair',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Havana',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Nebelung',
  'Norwegian Forest',
  'Ocicat',
  'Oriental Short Hair',
  'Persian',
  'Pixiebob',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx / Hairless',
  'Tonkinese',
  'Tortoiseshell',
  'Toyger',
  'Turkish Angora',
  'Tuxedo',
  'York Chocolate'];

export var colorOptions = [
  'Black',
  'Black & White / Tuxedo',
  'Blue Cream',
  'Blue Point',
  'Brown / Chocolate',
  'Buff & White',
  'Buff / Tan / Fawn',
  'Calico',
  'Chocolate Point',
  'Cream / Ivory',
  'Cream Point',
  'Dilute Calico',
  'Dilute Tortoiseshell',
  'Flame Point',
  'Gray & White',
  'Gray / Blue / Silver',
  'Lilac Point',
  'Orange & White',
  'Orange / Red',
  'Seal Point',
  'Smoke',
  'Tabby (Brown / Chocolate)',
  'Tabby (Buff / Tan / Fawn)',
  'Tabby (Gray / Blue / Silver)',
  'Tabby (Leopard / Spotted)',
  'Tabby (Orange / Red)',
  'Tabby (Tiger Striped)',
  'Torbie',
  'Tortoiseshell'
]
